channels:
  - conda-forge
dependencies:
  - r-base=4.4
  - r-tidyverse
  - r-desctools
  - r-lsr
  - r-ggplot2
  - r-irkernel  # To enable R kernel in Jupyter Notebooks
  - r-devtools  # Useful for package development (optional)
  - r-ggpubr    # Additional ggplot2 functions (optional)
  - r-data.table # For enhanced data manipulation (optional)
